### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by rsulliv1** [synclounge/synclounge#1035]
Anyone having this issue today?

Thrown a few times on startup. App fails to launch.

![Screenshot_20220601-214741_Chrome](https://user-images.githubusercontent.com/1417720/171542525-dc54a4b6-5a2b-4404-9bac-74880f215bf2.jpg)

**Comment by rsulliv1** [comment]
Using docker v 5.1.111 works.

**Comment by ttshivers** [comment]
The issue should be fixed as of [5.1.116](https://github.com/synclounge/synclounge/releases/tag/v5.1.116)
We had an issue updating to node v18 with syncloungeserver so we reverted the base image to use node16

**Comment by sausje** [comment]
> The issue should be fixed as of [5.1.116](https://github.com/synclounge/synclounge/releases/tag/v5.1.116) We had an issue updating to node v18 with syncloungeserver so we reverted the base image to use node16

As of 9 min ago 5.1.123 is still showing this error, on a very fresh docker install even. Am I understanding that this bug has been around for 9 revisions now??

**Comment by drizzt** [comment]
I still have this problem too, lol
